title: Metadata Documentation Testing
description: testing! 
theme: just-the-docs

url: https://janefiegel.github.io/mdtesting1/

permalink: pretty

enable_copy_code_button: true

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
